#
# Copyright (c) 2015, Prometheus Research, LLC
#

title: RIOS.CONVERISON
tests:
  # check Python source syntax and style
  - sh: flake8 ./src/
  
  - sh: pip install --quiet coverage nose
    ignore: true

  - sh: nosetests --quiet
    ignore: true
